// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

type DhcpOption struct {
	pulumi.CustomResourceState

	Default           pulumi.BoolOutput        `pulumi:"default"`
	DhcpOptionsSetId  pulumi.StringOutput      `pulumi:"dhcpOptionsSetId"`
	DomainName        pulumi.StringOutput      `pulumi:"domainName"`
	DomainNameServers pulumi.StringArrayOutput `pulumi:"domainNameServers"`
	LogServers        pulumi.StringArrayOutput `pulumi:"logServers"`
	NtpServers        pulumi.StringArrayOutput `pulumi:"ntpServers"`
	RequestId         pulumi.StringOutput      `pulumi:"requestId"`
	Tags              DhcpOptionTagArrayOutput `pulumi:"tags"`
}

// NewDhcpOption registers a new resource with the given unique name, arguments, and options.
func NewDhcpOption(ctx *pulumi.Context,
	name string, args *DhcpOptionArgs, opts ...pulumi.ResourceOption) (*DhcpOption, error) {
	if args == nil {
		args = &DhcpOptionArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource DhcpOption
	err := ctx.RegisterResource("outscale:index/dhcpOption:DhcpOption", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetDhcpOption gets an existing DhcpOption resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetDhcpOption(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *DhcpOptionState, opts ...pulumi.ResourceOption) (*DhcpOption, error) {
	var resource DhcpOption
	err := ctx.ReadResource("outscale:index/dhcpOption:DhcpOption", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering DhcpOption resources.
type dhcpOptionState struct {
	Default           *bool           `pulumi:"default"`
	DhcpOptionsSetId  *string         `pulumi:"dhcpOptionsSetId"`
	DomainName        *string         `pulumi:"domainName"`
	DomainNameServers []string        `pulumi:"domainNameServers"`
	LogServers        []string        `pulumi:"logServers"`
	NtpServers        []string        `pulumi:"ntpServers"`
	RequestId         *string         `pulumi:"requestId"`
	Tags              []DhcpOptionTag `pulumi:"tags"`
}

type DhcpOptionState struct {
	Default           pulumi.BoolPtrInput
	DhcpOptionsSetId  pulumi.StringPtrInput
	DomainName        pulumi.StringPtrInput
	DomainNameServers pulumi.StringArrayInput
	LogServers        pulumi.StringArrayInput
	NtpServers        pulumi.StringArrayInput
	RequestId         pulumi.StringPtrInput
	Tags              DhcpOptionTagArrayInput
}

func (DhcpOptionState) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpOptionState)(nil)).Elem()
}

type dhcpOptionArgs struct {
	DomainName        *string         `pulumi:"domainName"`
	DomainNameServers []string        `pulumi:"domainNameServers"`
	LogServers        []string        `pulumi:"logServers"`
	NtpServers        []string        `pulumi:"ntpServers"`
	Tags              []DhcpOptionTag `pulumi:"tags"`
}

// The set of arguments for constructing a DhcpOption resource.
type DhcpOptionArgs struct {
	DomainName        pulumi.StringPtrInput
	DomainNameServers pulumi.StringArrayInput
	LogServers        pulumi.StringArrayInput
	NtpServers        pulumi.StringArrayInput
	Tags              DhcpOptionTagArrayInput
}

func (DhcpOptionArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*dhcpOptionArgs)(nil)).Elem()
}

type DhcpOptionInput interface {
	pulumi.Input

	ToDhcpOptionOutput() DhcpOptionOutput
	ToDhcpOptionOutputWithContext(ctx context.Context) DhcpOptionOutput
}

func (*DhcpOption) ElementType() reflect.Type {
	return reflect.TypeOf((**DhcpOption)(nil)).Elem()
}

func (i *DhcpOption) ToDhcpOptionOutput() DhcpOptionOutput {
	return i.ToDhcpOptionOutputWithContext(context.Background())
}

func (i *DhcpOption) ToDhcpOptionOutputWithContext(ctx context.Context) DhcpOptionOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpOptionOutput)
}

func (i *DhcpOption) ToOutput(ctx context.Context) pulumix.Output[*DhcpOption] {
	return pulumix.Output[*DhcpOption]{
		OutputState: i.ToDhcpOptionOutputWithContext(ctx).OutputState,
	}
}

// DhcpOptionArrayInput is an input type that accepts DhcpOptionArray and DhcpOptionArrayOutput values.
// You can construct a concrete instance of `DhcpOptionArrayInput` via:
//
//	DhcpOptionArray{ DhcpOptionArgs{...} }
type DhcpOptionArrayInput interface {
	pulumi.Input

	ToDhcpOptionArrayOutput() DhcpOptionArrayOutput
	ToDhcpOptionArrayOutputWithContext(context.Context) DhcpOptionArrayOutput
}

type DhcpOptionArray []DhcpOptionInput

func (DhcpOptionArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DhcpOption)(nil)).Elem()
}

func (i DhcpOptionArray) ToDhcpOptionArrayOutput() DhcpOptionArrayOutput {
	return i.ToDhcpOptionArrayOutputWithContext(context.Background())
}

func (i DhcpOptionArray) ToDhcpOptionArrayOutputWithContext(ctx context.Context) DhcpOptionArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpOptionArrayOutput)
}

func (i DhcpOptionArray) ToOutput(ctx context.Context) pulumix.Output[[]*DhcpOption] {
	return pulumix.Output[[]*DhcpOption]{
		OutputState: i.ToDhcpOptionArrayOutputWithContext(ctx).OutputState,
	}
}

// DhcpOptionMapInput is an input type that accepts DhcpOptionMap and DhcpOptionMapOutput values.
// You can construct a concrete instance of `DhcpOptionMapInput` via:
//
//	DhcpOptionMap{ "key": DhcpOptionArgs{...} }
type DhcpOptionMapInput interface {
	pulumi.Input

	ToDhcpOptionMapOutput() DhcpOptionMapOutput
	ToDhcpOptionMapOutputWithContext(context.Context) DhcpOptionMapOutput
}

type DhcpOptionMap map[string]DhcpOptionInput

func (DhcpOptionMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DhcpOption)(nil)).Elem()
}

func (i DhcpOptionMap) ToDhcpOptionMapOutput() DhcpOptionMapOutput {
	return i.ToDhcpOptionMapOutputWithContext(context.Background())
}

func (i DhcpOptionMap) ToDhcpOptionMapOutputWithContext(ctx context.Context) DhcpOptionMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(DhcpOptionMapOutput)
}

func (i DhcpOptionMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*DhcpOption] {
	return pulumix.Output[map[string]*DhcpOption]{
		OutputState: i.ToDhcpOptionMapOutputWithContext(ctx).OutputState,
	}
}

type DhcpOptionOutput struct{ *pulumi.OutputState }

func (DhcpOptionOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**DhcpOption)(nil)).Elem()
}

func (o DhcpOptionOutput) ToDhcpOptionOutput() DhcpOptionOutput {
	return o
}

func (o DhcpOptionOutput) ToDhcpOptionOutputWithContext(ctx context.Context) DhcpOptionOutput {
	return o
}

func (o DhcpOptionOutput) ToOutput(ctx context.Context) pulumix.Output[*DhcpOption] {
	return pulumix.Output[*DhcpOption]{
		OutputState: o.OutputState,
	}
}

func (o DhcpOptionOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.BoolOutput { return v.Default }).(pulumi.BoolOutput)
}

func (o DhcpOptionOutput) DhcpOptionsSetId() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringOutput { return v.DhcpOptionsSetId }).(pulumi.StringOutput)
}

func (o DhcpOptionOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringOutput { return v.DomainName }).(pulumi.StringOutput)
}

func (o DhcpOptionOutput) DomainNameServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringArrayOutput { return v.DomainNameServers }).(pulumi.StringArrayOutput)
}

func (o DhcpOptionOutput) LogServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringArrayOutput { return v.LogServers }).(pulumi.StringArrayOutput)
}

func (o DhcpOptionOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringArrayOutput { return v.NtpServers }).(pulumi.StringArrayOutput)
}

func (o DhcpOptionOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *DhcpOption) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o DhcpOptionOutput) Tags() DhcpOptionTagArrayOutput {
	return o.ApplyT(func(v *DhcpOption) DhcpOptionTagArrayOutput { return v.Tags }).(DhcpOptionTagArrayOutput)
}

type DhcpOptionArrayOutput struct{ *pulumi.OutputState }

func (DhcpOptionArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*DhcpOption)(nil)).Elem()
}

func (o DhcpOptionArrayOutput) ToDhcpOptionArrayOutput() DhcpOptionArrayOutput {
	return o
}

func (o DhcpOptionArrayOutput) ToDhcpOptionArrayOutputWithContext(ctx context.Context) DhcpOptionArrayOutput {
	return o
}

func (o DhcpOptionArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*DhcpOption] {
	return pulumix.Output[[]*DhcpOption]{
		OutputState: o.OutputState,
	}
}

func (o DhcpOptionArrayOutput) Index(i pulumi.IntInput) DhcpOptionOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *DhcpOption {
		return vs[0].([]*DhcpOption)[vs[1].(int)]
	}).(DhcpOptionOutput)
}

type DhcpOptionMapOutput struct{ *pulumi.OutputState }

func (DhcpOptionMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*DhcpOption)(nil)).Elem()
}

func (o DhcpOptionMapOutput) ToDhcpOptionMapOutput() DhcpOptionMapOutput {
	return o
}

func (o DhcpOptionMapOutput) ToDhcpOptionMapOutputWithContext(ctx context.Context) DhcpOptionMapOutput {
	return o
}

func (o DhcpOptionMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*DhcpOption] {
	return pulumix.Output[map[string]*DhcpOption]{
		OutputState: o.OutputState,
	}
}

func (o DhcpOptionMapOutput) MapIndex(k pulumi.StringInput) DhcpOptionOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *DhcpOption {
		return vs[0].(map[string]*DhcpOption)[vs[1].(string)]
	}).(DhcpOptionOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpOptionInput)(nil)).Elem(), &DhcpOption{})
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpOptionArrayInput)(nil)).Elem(), DhcpOptionArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*DhcpOptionMapInput)(nil)).Elem(), DhcpOptionMap{})
	pulumi.RegisterOutputType(DhcpOptionOutput{})
	pulumi.RegisterOutputType(DhcpOptionArrayOutput{})
	pulumi.RegisterOutputType(DhcpOptionMapOutput{})
}
