// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetAccount(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetAccountResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetAccountResult
	err := ctx.Invoke("outscale:index/getAccount:getAccount", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getAccount.
type GetAccountResult struct {
	AccountId        string   `pulumi:"accountId"`
	AdditionalEmails []string `pulumi:"additionalEmails"`
	City             string   `pulumi:"city"`
	CompanyName      string   `pulumi:"companyName"`
	Country          string   `pulumi:"country"`
	CustomerId       string   `pulumi:"customerId"`
	Email            string   `pulumi:"email"`
	FirstName        string   `pulumi:"firstName"`
	// The provider-assigned unique ID for this managed resource.
	Id            string `pulumi:"id"`
	JobTitle      string `pulumi:"jobTitle"`
	LastName      string `pulumi:"lastName"`
	MobileNumber  string `pulumi:"mobileNumber"`
	PhoneNumber   string `pulumi:"phoneNumber"`
	RequestId     string `pulumi:"requestId"`
	StateProvince string `pulumi:"stateProvince"`
	VatNumber     string `pulumi:"vatNumber"`
	ZipCode       string `pulumi:"zipCode"`
}
