// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupAccessKey(ctx *pulumi.Context, args *LookupAccessKeyArgs, opts ...pulumi.InvokeOption) (*LookupAccessKeyResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupAccessKeyResult
	err := ctx.Invoke("outscale:index/getAccessKey:getAccessKey", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getAccessKey.
type LookupAccessKeyArgs struct {
	AccessKeyId *string              `pulumi:"accessKeyId"`
	Filters     []GetAccessKeyFilter `pulumi:"filters"`
	State       *string              `pulumi:"state"`
}

// A collection of values returned by getAccessKey.
type LookupAccessKeyResult struct {
	AccessKeyId    *string              `pulumi:"accessKeyId"`
	CreationDate   string               `pulumi:"creationDate"`
	ExpirationDate string               `pulumi:"expirationDate"`
	Filters        []GetAccessKeyFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id                   string  `pulumi:"id"`
	LastModificationDate string  `pulumi:"lastModificationDate"`
	RequestId            string  `pulumi:"requestId"`
	State                *string `pulumi:"state"`
}

func LookupAccessKeyOutput(ctx *pulumi.Context, args LookupAccessKeyOutputArgs, opts ...pulumi.InvokeOption) LookupAccessKeyResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupAccessKeyResult, error) {
			args := v.(LookupAccessKeyArgs)
			r, err := LookupAccessKey(ctx, &args, opts...)
			var s LookupAccessKeyResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupAccessKeyResultOutput)
}

// A collection of arguments for invoking getAccessKey.
type LookupAccessKeyOutputArgs struct {
	AccessKeyId pulumi.StringPtrInput        `pulumi:"accessKeyId"`
	Filters     GetAccessKeyFilterArrayInput `pulumi:"filters"`
	State       pulumi.StringPtrInput        `pulumi:"state"`
}

func (LookupAccessKeyOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccessKeyArgs)(nil)).Elem()
}

// A collection of values returned by getAccessKey.
type LookupAccessKeyResultOutput struct{ *pulumi.OutputState }

func (LookupAccessKeyResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupAccessKeyResult)(nil)).Elem()
}

func (o LookupAccessKeyResultOutput) ToLookupAccessKeyResultOutput() LookupAccessKeyResultOutput {
	return o
}

func (o LookupAccessKeyResultOutput) ToLookupAccessKeyResultOutputWithContext(ctx context.Context) LookupAccessKeyResultOutput {
	return o
}

func (o LookupAccessKeyResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupAccessKeyResult] {
	return pulumix.Output[LookupAccessKeyResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupAccessKeyResultOutput) AccessKeyId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) *string { return v.AccessKeyId }).(pulumi.StringPtrOutput)
}

func (o LookupAccessKeyResultOutput) CreationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) string { return v.CreationDate }).(pulumi.StringOutput)
}

func (o LookupAccessKeyResultOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) string { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o LookupAccessKeyResultOutput) Filters() GetAccessKeyFilterArrayOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) []GetAccessKeyFilter { return v.Filters }).(GetAccessKeyFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupAccessKeyResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupAccessKeyResultOutput) LastModificationDate() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) string { return v.LastModificationDate }).(pulumi.StringOutput)
}

func (o LookupAccessKeyResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupAccessKeyResultOutput) State() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupAccessKeyResult) *string { return v.State }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupAccessKeyResultOutput{})
}
