// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupClientGateway(ctx *pulumi.Context, args *LookupClientGatewayArgs, opts ...pulumi.InvokeOption) (*LookupClientGatewayResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupClientGatewayResult
	err := ctx.Invoke("outscale:index/getClientGateway:getClientGateway", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getClientGateway.
type LookupClientGatewayArgs struct {
	ClientGatewayId *string                  `pulumi:"clientGatewayId"`
	Filters         []GetClientGatewayFilter `pulumi:"filters"`
}

// A collection of values returned by getClientGateway.
type LookupClientGatewayResult struct {
	BgpAsn          int                      `pulumi:"bgpAsn"`
	ClientGatewayId *string                  `pulumi:"clientGatewayId"`
	ConnectionType  string                   `pulumi:"connectionType"`
	Filters         []GetClientGatewayFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id        string                `pulumi:"id"`
	PublicIp  string                `pulumi:"publicIp"`
	RequestId string                `pulumi:"requestId"`
	State     string                `pulumi:"state"`
	Tags      []GetClientGatewayTag `pulumi:"tags"`
}

func LookupClientGatewayOutput(ctx *pulumi.Context, args LookupClientGatewayOutputArgs, opts ...pulumi.InvokeOption) LookupClientGatewayResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupClientGatewayResult, error) {
			args := v.(LookupClientGatewayArgs)
			r, err := LookupClientGateway(ctx, &args, opts...)
			var s LookupClientGatewayResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupClientGatewayResultOutput)
}

// A collection of arguments for invoking getClientGateway.
type LookupClientGatewayOutputArgs struct {
	ClientGatewayId pulumi.StringPtrInput            `pulumi:"clientGatewayId"`
	Filters         GetClientGatewayFilterArrayInput `pulumi:"filters"`
}

func (LookupClientGatewayOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientGatewayArgs)(nil)).Elem()
}

// A collection of values returned by getClientGateway.
type LookupClientGatewayResultOutput struct{ *pulumi.OutputState }

func (LookupClientGatewayResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupClientGatewayResult)(nil)).Elem()
}

func (o LookupClientGatewayResultOutput) ToLookupClientGatewayResultOutput() LookupClientGatewayResultOutput {
	return o
}

func (o LookupClientGatewayResultOutput) ToLookupClientGatewayResultOutputWithContext(ctx context.Context) LookupClientGatewayResultOutput {
	return o
}

func (o LookupClientGatewayResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupClientGatewayResult] {
	return pulumix.Output[LookupClientGatewayResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupClientGatewayResultOutput) BgpAsn() pulumi.IntOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) int { return v.BgpAsn }).(pulumi.IntOutput)
}

func (o LookupClientGatewayResultOutput) ClientGatewayId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) *string { return v.ClientGatewayId }).(pulumi.StringPtrOutput)
}

func (o LookupClientGatewayResultOutput) ConnectionType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.ConnectionType }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) Filters() GetClientGatewayFilterArrayOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) []GetClientGatewayFilter { return v.Filters }).(GetClientGatewayFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupClientGatewayResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupClientGatewayResultOutput) Tags() GetClientGatewayTagArrayOutput {
	return o.ApplyT(func(v LookupClientGatewayResult) []GetClientGatewayTag { return v.Tags }).(GetClientGatewayTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupClientGatewayResultOutput{})
}
