// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupDhcpOption(ctx *pulumi.Context, args *LookupDhcpOptionArgs, opts ...pulumi.InvokeOption) (*LookupDhcpOptionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupDhcpOptionResult
	err := ctx.Invoke("outscale:index/getDhcpOption:getDhcpOption", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDhcpOption.
type LookupDhcpOptionArgs struct {
	Filters []GetDhcpOptionFilter `pulumi:"filters"`
}

// A collection of values returned by getDhcpOption.
type LookupDhcpOptionResult struct {
	Default           bool                  `pulumi:"default"`
	DhcpOptionsSetId  string                `pulumi:"dhcpOptionsSetId"`
	DomainName        string                `pulumi:"domainName"`
	DomainNameServers []string              `pulumi:"domainNameServers"`
	Filters           []GetDhcpOptionFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id         string             `pulumi:"id"`
	LogServers []string           `pulumi:"logServers"`
	NtpServers []string           `pulumi:"ntpServers"`
	RequestId  string             `pulumi:"requestId"`
	Tags       []GetDhcpOptionTag `pulumi:"tags"`
}

func LookupDhcpOptionOutput(ctx *pulumi.Context, args LookupDhcpOptionOutputArgs, opts ...pulumi.InvokeOption) LookupDhcpOptionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupDhcpOptionResult, error) {
			args := v.(LookupDhcpOptionArgs)
			r, err := LookupDhcpOption(ctx, &args, opts...)
			var s LookupDhcpOptionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupDhcpOptionResultOutput)
}

// A collection of arguments for invoking getDhcpOption.
type LookupDhcpOptionOutputArgs struct {
	Filters GetDhcpOptionFilterArrayInput `pulumi:"filters"`
}

func (LookupDhcpOptionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDhcpOptionArgs)(nil)).Elem()
}

// A collection of values returned by getDhcpOption.
type LookupDhcpOptionResultOutput struct{ *pulumi.OutputState }

func (LookupDhcpOptionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupDhcpOptionResult)(nil)).Elem()
}

func (o LookupDhcpOptionResultOutput) ToLookupDhcpOptionResultOutput() LookupDhcpOptionResultOutput {
	return o
}

func (o LookupDhcpOptionResultOutput) ToLookupDhcpOptionResultOutputWithContext(ctx context.Context) LookupDhcpOptionResultOutput {
	return o
}

func (o LookupDhcpOptionResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupDhcpOptionResult] {
	return pulumix.Output[LookupDhcpOptionResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupDhcpOptionResultOutput) Default() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) bool { return v.Default }).(pulumi.BoolOutput)
}

func (o LookupDhcpOptionResultOutput) DhcpOptionsSetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) string { return v.DhcpOptionsSetId }).(pulumi.StringOutput)
}

func (o LookupDhcpOptionResultOutput) DomainName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) string { return v.DomainName }).(pulumi.StringOutput)
}

func (o LookupDhcpOptionResultOutput) DomainNameServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) []string { return v.DomainNameServers }).(pulumi.StringArrayOutput)
}

func (o LookupDhcpOptionResultOutput) Filters() GetDhcpOptionFilterArrayOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) []GetDhcpOptionFilter { return v.Filters }).(GetDhcpOptionFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupDhcpOptionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupDhcpOptionResultOutput) LogServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) []string { return v.LogServers }).(pulumi.StringArrayOutput)
}

func (o LookupDhcpOptionResultOutput) NtpServers() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) []string { return v.NtpServers }).(pulumi.StringArrayOutput)
}

func (o LookupDhcpOptionResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupDhcpOptionResultOutput) Tags() GetDhcpOptionTagArrayOutput {
	return o.ApplyT(func(v LookupDhcpOptionResult) []GetDhcpOptionTag { return v.Tags }).(GetDhcpOptionTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupDhcpOptionResultOutput{})
}
