// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetDhcpOptions(ctx *pulumi.Context, args *GetDhcpOptionsArgs, opts ...pulumi.InvokeOption) (*GetDhcpOptionsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetDhcpOptionsResult
	err := ctx.Invoke("outscale:index/getDhcpOptions:getDhcpOptions", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getDhcpOptions.
type GetDhcpOptionsArgs struct {
	Filters []GetDhcpOptionsFilter `pulumi:"filters"`
}

// A collection of values returned by getDhcpOptions.
type GetDhcpOptionsResult struct {
	DhcpOptions       []GetDhcpOptionsDhcpOption `pulumi:"dhcpOptions"`
	DhcpOptionsSetIds []string                   `pulumi:"dhcpOptionsSetIds"`
	Filters           []GetDhcpOptionsFilter     `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	RequestId string `pulumi:"requestId"`
}

func GetDhcpOptionsOutput(ctx *pulumi.Context, args GetDhcpOptionsOutputArgs, opts ...pulumi.InvokeOption) GetDhcpOptionsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetDhcpOptionsResult, error) {
			args := v.(GetDhcpOptionsArgs)
			r, err := GetDhcpOptions(ctx, &args, opts...)
			var s GetDhcpOptionsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetDhcpOptionsResultOutput)
}

// A collection of arguments for invoking getDhcpOptions.
type GetDhcpOptionsOutputArgs struct {
	Filters GetDhcpOptionsFilterArrayInput `pulumi:"filters"`
}

func (GetDhcpOptionsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDhcpOptionsArgs)(nil)).Elem()
}

// A collection of values returned by getDhcpOptions.
type GetDhcpOptionsResultOutput struct{ *pulumi.OutputState }

func (GetDhcpOptionsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetDhcpOptionsResult)(nil)).Elem()
}

func (o GetDhcpOptionsResultOutput) ToGetDhcpOptionsResultOutput() GetDhcpOptionsResultOutput {
	return o
}

func (o GetDhcpOptionsResultOutput) ToGetDhcpOptionsResultOutputWithContext(ctx context.Context) GetDhcpOptionsResultOutput {
	return o
}

func (o GetDhcpOptionsResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetDhcpOptionsResult] {
	return pulumix.Output[GetDhcpOptionsResult]{
		OutputState: o.OutputState,
	}
}

func (o GetDhcpOptionsResultOutput) DhcpOptions() GetDhcpOptionsDhcpOptionArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []GetDhcpOptionsDhcpOption { return v.DhcpOptions }).(GetDhcpOptionsDhcpOptionArrayOutput)
}

func (o GetDhcpOptionsResultOutput) DhcpOptionsSetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []string { return v.DhcpOptionsSetIds }).(pulumi.StringArrayOutput)
}

func (o GetDhcpOptionsResultOutput) Filters() GetDhcpOptionsFilterArrayOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) []GetDhcpOptionsFilter { return v.Filters }).(GetDhcpOptionsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetDhcpOptionsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetDhcpOptionsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetDhcpOptionsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetDhcpOptionsResultOutput{})
}
