// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupFlexibleGpu(ctx *pulumi.Context, args *LookupFlexibleGpuArgs, opts ...pulumi.InvokeOption) (*LookupFlexibleGpuResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupFlexibleGpuResult
	err := ctx.Invoke("outscale:index/getFlexibleGpu:getFlexibleGpu", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getFlexibleGpu.
type LookupFlexibleGpuArgs struct {
	Filters []GetFlexibleGpuFilter `pulumi:"filters"`
}

// A collection of values returned by getFlexibleGpu.
type LookupFlexibleGpuResult struct {
	DeleteOnVmDeletion bool                   `pulumi:"deleteOnVmDeletion"`
	Filters            []GetFlexibleGpuFilter `pulumi:"filters"`
	FlexibleGpuId      string                 `pulumi:"flexibleGpuId"`
	Generation         string                 `pulumi:"generation"`
	// The provider-assigned unique ID for this managed resource.
	Id            string `pulumi:"id"`
	ModelName     string `pulumi:"modelName"`
	RequestId     string `pulumi:"requestId"`
	State         string `pulumi:"state"`
	SubregionName string `pulumi:"subregionName"`
	VmId          string `pulumi:"vmId"`
}

func LookupFlexibleGpuOutput(ctx *pulumi.Context, args LookupFlexibleGpuOutputArgs, opts ...pulumi.InvokeOption) LookupFlexibleGpuResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupFlexibleGpuResult, error) {
			args := v.(LookupFlexibleGpuArgs)
			r, err := LookupFlexibleGpu(ctx, &args, opts...)
			var s LookupFlexibleGpuResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupFlexibleGpuResultOutput)
}

// A collection of arguments for invoking getFlexibleGpu.
type LookupFlexibleGpuOutputArgs struct {
	Filters GetFlexibleGpuFilterArrayInput `pulumi:"filters"`
}

func (LookupFlexibleGpuOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFlexibleGpuArgs)(nil)).Elem()
}

// A collection of values returned by getFlexibleGpu.
type LookupFlexibleGpuResultOutput struct{ *pulumi.OutputState }

func (LookupFlexibleGpuResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupFlexibleGpuResult)(nil)).Elem()
}

func (o LookupFlexibleGpuResultOutput) ToLookupFlexibleGpuResultOutput() LookupFlexibleGpuResultOutput {
	return o
}

func (o LookupFlexibleGpuResultOutput) ToLookupFlexibleGpuResultOutputWithContext(ctx context.Context) LookupFlexibleGpuResultOutput {
	return o
}

func (o LookupFlexibleGpuResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupFlexibleGpuResult] {
	return pulumix.Output[LookupFlexibleGpuResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupFlexibleGpuResultOutput) DeleteOnVmDeletion() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) bool { return v.DeleteOnVmDeletion }).(pulumi.BoolOutput)
}

func (o LookupFlexibleGpuResultOutput) Filters() GetFlexibleGpuFilterArrayOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) []GetFlexibleGpuFilter { return v.Filters }).(GetFlexibleGpuFilterArrayOutput)
}

func (o LookupFlexibleGpuResultOutput) FlexibleGpuId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.FlexibleGpuId }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) Generation() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.Generation }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupFlexibleGpuResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) ModelName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.ModelName }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) SubregionName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.SubregionName }).(pulumi.StringOutput)
}

func (o LookupFlexibleGpuResultOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupFlexibleGpuResult) string { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupFlexibleGpuResultOutput{})
}
