// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetInternetServices(ctx *pulumi.Context, args *GetInternetServicesArgs, opts ...pulumi.InvokeOption) (*GetInternetServicesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetInternetServicesResult
	err := ctx.Invoke("outscale:index/getInternetServices:getInternetServices", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getInternetServices.
type GetInternetServicesArgs struct {
	Filters            []GetInternetServicesFilter `pulumi:"filters"`
	InternetServiceIds []string                    `pulumi:"internetServiceIds"`
}

// A collection of values returned by getInternetServices.
type GetInternetServicesResult struct {
	Filters []GetInternetServicesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id                 string                               `pulumi:"id"`
	InternetServiceIds []string                             `pulumi:"internetServiceIds"`
	InternetServices   []GetInternetServicesInternetService `pulumi:"internetServices"`
	RequestId          string                               `pulumi:"requestId"`
}

func GetInternetServicesOutput(ctx *pulumi.Context, args GetInternetServicesOutputArgs, opts ...pulumi.InvokeOption) GetInternetServicesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetInternetServicesResult, error) {
			args := v.(GetInternetServicesArgs)
			r, err := GetInternetServices(ctx, &args, opts...)
			var s GetInternetServicesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetInternetServicesResultOutput)
}

// A collection of arguments for invoking getInternetServices.
type GetInternetServicesOutputArgs struct {
	Filters            GetInternetServicesFilterArrayInput `pulumi:"filters"`
	InternetServiceIds pulumi.StringArrayInput             `pulumi:"internetServiceIds"`
}

func (GetInternetServicesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInternetServicesArgs)(nil)).Elem()
}

// A collection of values returned by getInternetServices.
type GetInternetServicesResultOutput struct{ *pulumi.OutputState }

func (GetInternetServicesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetInternetServicesResult)(nil)).Elem()
}

func (o GetInternetServicesResultOutput) ToGetInternetServicesResultOutput() GetInternetServicesResultOutput {
	return o
}

func (o GetInternetServicesResultOutput) ToGetInternetServicesResultOutputWithContext(ctx context.Context) GetInternetServicesResultOutput {
	return o
}

func (o GetInternetServicesResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetInternetServicesResult] {
	return pulumix.Output[GetInternetServicesResult]{
		OutputState: o.OutputState,
	}
}

func (o GetInternetServicesResultOutput) Filters() GetInternetServicesFilterArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []GetInternetServicesFilter { return v.Filters }).(GetInternetServicesFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetInternetServicesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetInternetServicesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetInternetServicesResultOutput) InternetServiceIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []string { return v.InternetServiceIds }).(pulumi.StringArrayOutput)
}

func (o GetInternetServicesResultOutput) InternetServices() GetInternetServicesInternetServiceArrayOutput {
	return o.ApplyT(func(v GetInternetServicesResult) []GetInternetServicesInternetService { return v.InternetServices }).(GetInternetServicesInternetServiceArrayOutput)
}

func (o GetInternetServicesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetInternetServicesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetInternetServicesResultOutput{})
}
