// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetLoadBalancers(ctx *pulumi.Context, args *GetLoadBalancersArgs, opts ...pulumi.InvokeOption) (*GetLoadBalancersResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetLoadBalancersResult
	err := ctx.Invoke("outscale:index/getLoadBalancers:getLoadBalancers", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getLoadBalancers.
type GetLoadBalancersArgs struct {
	Filters           []GetLoadBalancersFilter `pulumi:"filters"`
	LoadBalancerNames []string                 `pulumi:"loadBalancerNames"`
}

// A collection of values returned by getLoadBalancers.
type GetLoadBalancersResult struct {
	Filters []GetLoadBalancersFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                         `pulumi:"id"`
	LoadBalancerNames []string                       `pulumi:"loadBalancerNames"`
	LoadBalancers     []GetLoadBalancersLoadBalancer `pulumi:"loadBalancers"`
	RequestId         string                         `pulumi:"requestId"`
}

func GetLoadBalancersOutput(ctx *pulumi.Context, args GetLoadBalancersOutputArgs, opts ...pulumi.InvokeOption) GetLoadBalancersResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetLoadBalancersResult, error) {
			args := v.(GetLoadBalancersArgs)
			r, err := GetLoadBalancers(ctx, &args, opts...)
			var s GetLoadBalancersResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetLoadBalancersResultOutput)
}

// A collection of arguments for invoking getLoadBalancers.
type GetLoadBalancersOutputArgs struct {
	Filters           GetLoadBalancersFilterArrayInput `pulumi:"filters"`
	LoadBalancerNames pulumi.StringArrayInput          `pulumi:"loadBalancerNames"`
}

func (GetLoadBalancersOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoadBalancersArgs)(nil)).Elem()
}

// A collection of values returned by getLoadBalancers.
type GetLoadBalancersResultOutput struct{ *pulumi.OutputState }

func (GetLoadBalancersResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetLoadBalancersResult)(nil)).Elem()
}

func (o GetLoadBalancersResultOutput) ToGetLoadBalancersResultOutput() GetLoadBalancersResultOutput {
	return o
}

func (o GetLoadBalancersResultOutput) ToGetLoadBalancersResultOutputWithContext(ctx context.Context) GetLoadBalancersResultOutput {
	return o
}

func (o GetLoadBalancersResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetLoadBalancersResult] {
	return pulumix.Output[GetLoadBalancersResult]{
		OutputState: o.OutputState,
	}
}

func (o GetLoadBalancersResultOutput) Filters() GetLoadBalancersFilterArrayOutput {
	return o.ApplyT(func(v GetLoadBalancersResult) []GetLoadBalancersFilter { return v.Filters }).(GetLoadBalancersFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetLoadBalancersResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetLoadBalancersResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetLoadBalancersResultOutput) LoadBalancerNames() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetLoadBalancersResult) []string { return v.LoadBalancerNames }).(pulumi.StringArrayOutput)
}

func (o GetLoadBalancersResultOutput) LoadBalancers() GetLoadBalancersLoadBalancerArrayOutput {
	return o.ApplyT(func(v GetLoadBalancersResult) []GetLoadBalancersLoadBalancer { return v.LoadBalancers }).(GetLoadBalancersLoadBalancerArrayOutput)
}

func (o GetLoadBalancersResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetLoadBalancersResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetLoadBalancersResultOutput{})
}
