// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupNatService(ctx *pulumi.Context, args *LookupNatServiceArgs, opts ...pulumi.InvokeOption) (*LookupNatServiceResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNatServiceResult
	err := ctx.Invoke("outscale:index/getNatService:getNatService", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNatService.
type LookupNatServiceArgs struct {
	Filters      []GetNatServiceFilter `pulumi:"filters"`
	NatServiceId *string               `pulumi:"natServiceId"`
}

// A collection of values returned by getNatService.
type LookupNatServiceResult struct {
	Filters []GetNatServiceFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id           string                  `pulumi:"id"`
	NatServiceId *string                 `pulumi:"natServiceId"`
	NetId        string                  `pulumi:"netId"`
	PublicIps    []GetNatServicePublicIp `pulumi:"publicIps"`
	RequestId    string                  `pulumi:"requestId"`
	State        string                  `pulumi:"state"`
	SubnetId     string                  `pulumi:"subnetId"`
	Tags         []GetNatServiceTag      `pulumi:"tags"`
}

func LookupNatServiceOutput(ctx *pulumi.Context, args LookupNatServiceOutputArgs, opts ...pulumi.InvokeOption) LookupNatServiceResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNatServiceResult, error) {
			args := v.(LookupNatServiceArgs)
			r, err := LookupNatService(ctx, &args, opts...)
			var s LookupNatServiceResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNatServiceResultOutput)
}

// A collection of arguments for invoking getNatService.
type LookupNatServiceOutputArgs struct {
	Filters      GetNatServiceFilterArrayInput `pulumi:"filters"`
	NatServiceId pulumi.StringPtrInput         `pulumi:"natServiceId"`
}

func (LookupNatServiceOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNatServiceArgs)(nil)).Elem()
}

// A collection of values returned by getNatService.
type LookupNatServiceResultOutput struct{ *pulumi.OutputState }

func (LookupNatServiceResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNatServiceResult)(nil)).Elem()
}

func (o LookupNatServiceResultOutput) ToLookupNatServiceResultOutput() LookupNatServiceResultOutput {
	return o
}

func (o LookupNatServiceResultOutput) ToLookupNatServiceResultOutputWithContext(ctx context.Context) LookupNatServiceResultOutput {
	return o
}

func (o LookupNatServiceResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupNatServiceResult] {
	return pulumix.Output[LookupNatServiceResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupNatServiceResultOutput) Filters() GetNatServiceFilterArrayOutput {
	return o.ApplyT(func(v LookupNatServiceResult) []GetNatServiceFilter { return v.Filters }).(GetNatServiceFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNatServiceResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNatServiceResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNatServiceResultOutput) NatServiceId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupNatServiceResult) *string { return v.NatServiceId }).(pulumi.StringPtrOutput)
}

func (o LookupNatServiceResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNatServiceResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupNatServiceResultOutput) PublicIps() GetNatServicePublicIpArrayOutput {
	return o.ApplyT(func(v LookupNatServiceResult) []GetNatServicePublicIp { return v.PublicIps }).(GetNatServicePublicIpArrayOutput)
}

func (o LookupNatServiceResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNatServiceResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupNatServiceResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNatServiceResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNatServiceResultOutput) SubnetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNatServiceResult) string { return v.SubnetId }).(pulumi.StringOutput)
}

func (o LookupNatServiceResultOutput) Tags() GetNatServiceTagArrayOutput {
	return o.ApplyT(func(v LookupNatServiceResult) []GetNatServiceTag { return v.Tags }).(GetNatServiceTagArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNatServiceResultOutput{})
}
