// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupNetAttributes(ctx *pulumi.Context, args *LookupNetAttributesArgs, opts ...pulumi.InvokeOption) (*LookupNetAttributesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupNetAttributesResult
	err := ctx.Invoke("outscale:index/getNetAttributes:getNetAttributes", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getNetAttributes.
type LookupNetAttributesArgs struct {
	NetId string `pulumi:"netId"`
}

// A collection of values returned by getNetAttributes.
type LookupNetAttributesResult struct {
	DhcpOptionsSetId string `pulumi:"dhcpOptionsSetId"`
	// The provider-assigned unique ID for this managed resource.
	Id        string                `pulumi:"id"`
	IpRange   string                `pulumi:"ipRange"`
	NetId     string                `pulumi:"netId"`
	RequestId string                `pulumi:"requestId"`
	State     string                `pulumi:"state"`
	Tags      []GetNetAttributesTag `pulumi:"tags"`
	Tenancy   string                `pulumi:"tenancy"`
}

func LookupNetAttributesOutput(ctx *pulumi.Context, args LookupNetAttributesOutputArgs, opts ...pulumi.InvokeOption) LookupNetAttributesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupNetAttributesResult, error) {
			args := v.(LookupNetAttributesArgs)
			r, err := LookupNetAttributes(ctx, &args, opts...)
			var s LookupNetAttributesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupNetAttributesResultOutput)
}

// A collection of arguments for invoking getNetAttributes.
type LookupNetAttributesOutputArgs struct {
	NetId pulumi.StringInput `pulumi:"netId"`
}

func (LookupNetAttributesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAttributesArgs)(nil)).Elem()
}

// A collection of values returned by getNetAttributes.
type LookupNetAttributesResultOutput struct{ *pulumi.OutputState }

func (LookupNetAttributesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupNetAttributesResult)(nil)).Elem()
}

func (o LookupNetAttributesResultOutput) ToLookupNetAttributesResultOutput() LookupNetAttributesResultOutput {
	return o
}

func (o LookupNetAttributesResultOutput) ToLookupNetAttributesResultOutputWithContext(ctx context.Context) LookupNetAttributesResultOutput {
	return o
}

func (o LookupNetAttributesResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupNetAttributesResult] {
	return pulumix.Output[LookupNetAttributesResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupNetAttributesResultOutput) DhcpOptionsSetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.DhcpOptionsSetId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupNetAttributesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) IpRange() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.IpRange }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) NetId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.NetId }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupNetAttributesResultOutput) Tags() GetNetAttributesTagArrayOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) []GetNetAttributesTag { return v.Tags }).(GetNetAttributesTagArrayOutput)
}

func (o LookupNetAttributesResultOutput) Tenancy() pulumi.StringOutput {
	return o.ApplyT(func(v LookupNetAttributesResult) string { return v.Tenancy }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupNetAttributesResultOutput{})
}
