// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupPublicIp(ctx *pulumi.Context, args *LookupPublicIpArgs, opts ...pulumi.InvokeOption) (*LookupPublicIpResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupPublicIpResult
	err := ctx.Invoke("outscale:index/getPublicIp:getPublicIp", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getPublicIp.
type LookupPublicIpArgs struct {
	Filters    []GetPublicIpFilter `pulumi:"filters"`
	PublicIp   *string             `pulumi:"publicIp"`
	PublicIpId *string             `pulumi:"publicIpId"`
}

// A collection of values returned by getPublicIp.
type LookupPublicIpResult struct {
	Filters []GetPublicIpFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id             string           `pulumi:"id"`
	LinkPublicIpId string           `pulumi:"linkPublicIpId"`
	NicAccountId   string           `pulumi:"nicAccountId"`
	NicId          string           `pulumi:"nicId"`
	PrivateIp      string           `pulumi:"privateIp"`
	PublicIp       string           `pulumi:"publicIp"`
	PublicIpId     string           `pulumi:"publicIpId"`
	RequestId      string           `pulumi:"requestId"`
	Tags           []GetPublicIpTag `pulumi:"tags"`
	VmId           string           `pulumi:"vmId"`
}

func LookupPublicIpOutput(ctx *pulumi.Context, args LookupPublicIpOutputArgs, opts ...pulumi.InvokeOption) LookupPublicIpResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupPublicIpResult, error) {
			args := v.(LookupPublicIpArgs)
			r, err := LookupPublicIp(ctx, &args, opts...)
			var s LookupPublicIpResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupPublicIpResultOutput)
}

// A collection of arguments for invoking getPublicIp.
type LookupPublicIpOutputArgs struct {
	Filters    GetPublicIpFilterArrayInput `pulumi:"filters"`
	PublicIp   pulumi.StringPtrInput       `pulumi:"publicIp"`
	PublicIpId pulumi.StringPtrInput       `pulumi:"publicIpId"`
}

func (LookupPublicIpOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPublicIpArgs)(nil)).Elem()
}

// A collection of values returned by getPublicIp.
type LookupPublicIpResultOutput struct{ *pulumi.OutputState }

func (LookupPublicIpResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupPublicIpResult)(nil)).Elem()
}

func (o LookupPublicIpResultOutput) ToLookupPublicIpResultOutput() LookupPublicIpResultOutput {
	return o
}

func (o LookupPublicIpResultOutput) ToLookupPublicIpResultOutputWithContext(ctx context.Context) LookupPublicIpResultOutput {
	return o
}

func (o LookupPublicIpResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupPublicIpResult] {
	return pulumix.Output[LookupPublicIpResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupPublicIpResultOutput) Filters() GetPublicIpFilterArrayOutput {
	return o.ApplyT(func(v LookupPublicIpResult) []GetPublicIpFilter { return v.Filters }).(GetPublicIpFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupPublicIpResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) LinkPublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.LinkPublicIpId }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) NicAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.NicAccountId }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) NicId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.NicId }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) PrivateIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.PrivateIp }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) PublicIp() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.PublicIp }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) PublicIpId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.PublicIpId }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupPublicIpResultOutput) Tags() GetPublicIpTagArrayOutput {
	return o.ApplyT(func(v LookupPublicIpResult) []GetPublicIpTag { return v.Tags }).(GetPublicIpTagArrayOutput)
}

func (o LookupPublicIpResultOutput) VmId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupPublicIpResult) string { return v.VmId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupPublicIpResultOutput{})
}
