// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

func GetPulicCatalog(ctx *pulumi.Context, opts ...pulumi.InvokeOption) (*GetPulicCatalogResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetPulicCatalogResult
	err := ctx.Invoke("outscale:index/getPulicCatalog:getPulicCatalog", nil, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of values returned by getPulicCatalog.
type GetPulicCatalogResult struct {
	Catalogs []GetPulicCatalogCatalog `pulumi:"catalogs"`
	// The provider-assigned unique ID for this managed resource.
	Id        string `pulumi:"id"`
	RequestId string `pulumi:"requestId"`
}
