// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupSnapshotExportTask(ctx *pulumi.Context, args *LookupSnapshotExportTaskArgs, opts ...pulumi.InvokeOption) (*LookupSnapshotExportTaskResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupSnapshotExportTaskResult
	err := ctx.Invoke("outscale:index/getSnapshotExportTask:getSnapshotExportTask", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getSnapshotExportTask.
type LookupSnapshotExportTaskArgs struct {
	DryRun  *bool                         `pulumi:"dryRun"`
	Filters []GetSnapshotExportTaskFilter `pulumi:"filters"`
}

// A collection of values returned by getSnapshotExportTask.
type LookupSnapshotExportTaskResult struct {
	Comment string                        `pulumi:"comment"`
	DryRun  bool                          `pulumi:"dryRun"`
	Filters []GetSnapshotExportTaskFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id         string                           `pulumi:"id"`
	OsuExports []GetSnapshotExportTaskOsuExport `pulumi:"osuExports"`
	Progress   int                              `pulumi:"progress"`
	RequestId  string                           `pulumi:"requestId"`
	SnapshotId string                           `pulumi:"snapshotId"`
	State      string                           `pulumi:"state"`
	Tags       []GetSnapshotExportTaskTag       `pulumi:"tags"`
	TaskId     string                           `pulumi:"taskId"`
}

func LookupSnapshotExportTaskOutput(ctx *pulumi.Context, args LookupSnapshotExportTaskOutputArgs, opts ...pulumi.InvokeOption) LookupSnapshotExportTaskResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupSnapshotExportTaskResult, error) {
			args := v.(LookupSnapshotExportTaskArgs)
			r, err := LookupSnapshotExportTask(ctx, &args, opts...)
			var s LookupSnapshotExportTaskResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupSnapshotExportTaskResultOutput)
}

// A collection of arguments for invoking getSnapshotExportTask.
type LookupSnapshotExportTaskOutputArgs struct {
	DryRun  pulumi.BoolPtrInput                   `pulumi:"dryRun"`
	Filters GetSnapshotExportTaskFilterArrayInput `pulumi:"filters"`
}

func (LookupSnapshotExportTaskOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSnapshotExportTaskArgs)(nil)).Elem()
}

// A collection of values returned by getSnapshotExportTask.
type LookupSnapshotExportTaskResultOutput struct{ *pulumi.OutputState }

func (LookupSnapshotExportTaskResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupSnapshotExportTaskResult)(nil)).Elem()
}

func (o LookupSnapshotExportTaskResultOutput) ToLookupSnapshotExportTaskResultOutput() LookupSnapshotExportTaskResultOutput {
	return o
}

func (o LookupSnapshotExportTaskResultOutput) ToLookupSnapshotExportTaskResultOutputWithContext(ctx context.Context) LookupSnapshotExportTaskResultOutput {
	return o
}

func (o LookupSnapshotExportTaskResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupSnapshotExportTaskResult] {
	return pulumix.Output[LookupSnapshotExportTaskResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupSnapshotExportTaskResultOutput) Comment() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.Comment }).(pulumi.StringOutput)
}

func (o LookupSnapshotExportTaskResultOutput) DryRun() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) bool { return v.DryRun }).(pulumi.BoolOutput)
}

func (o LookupSnapshotExportTaskResultOutput) Filters() GetSnapshotExportTaskFilterArrayOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) []GetSnapshotExportTaskFilter { return v.Filters }).(GetSnapshotExportTaskFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupSnapshotExportTaskResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupSnapshotExportTaskResultOutput) OsuExports() GetSnapshotExportTaskOsuExportArrayOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) []GetSnapshotExportTaskOsuExport { return v.OsuExports }).(GetSnapshotExportTaskOsuExportArrayOutput)
}

func (o LookupSnapshotExportTaskResultOutput) Progress() pulumi.IntOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) int { return v.Progress }).(pulumi.IntOutput)
}

func (o LookupSnapshotExportTaskResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupSnapshotExportTaskResultOutput) SnapshotId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.SnapshotId }).(pulumi.StringOutput)
}

func (o LookupSnapshotExportTaskResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupSnapshotExportTaskResultOutput) Tags() GetSnapshotExportTaskTagArrayOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) []GetSnapshotExportTaskTag { return v.Tags }).(GetSnapshotExportTaskTagArrayOutput)
}

func (o LookupSnapshotExportTaskResultOutput) TaskId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupSnapshotExportTaskResult) string { return v.TaskId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupSnapshotExportTaskResultOutput{})
}
