// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetVirtualGateways(ctx *pulumi.Context, args *GetVirtualGatewaysArgs, opts ...pulumi.InvokeOption) (*GetVirtualGatewaysResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVirtualGatewaysResult
	err := ctx.Invoke("outscale:index/getVirtualGateways:getVirtualGateways", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVirtualGateways.
type GetVirtualGatewaysArgs struct {
	Filters           []GetVirtualGatewaysFilter `pulumi:"filters"`
	VirtualGatewayIds []string                   `pulumi:"virtualGatewayIds"`
}

// A collection of values returned by getVirtualGateways.
type GetVirtualGatewaysResult struct {
	Filters []GetVirtualGatewaysFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id                string                             `pulumi:"id"`
	RequestId         string                             `pulumi:"requestId"`
	VirtualGatewayIds []string                           `pulumi:"virtualGatewayIds"`
	VirtualGateways   []GetVirtualGatewaysVirtualGateway `pulumi:"virtualGateways"`
}

func GetVirtualGatewaysOutput(ctx *pulumi.Context, args GetVirtualGatewaysOutputArgs, opts ...pulumi.InvokeOption) GetVirtualGatewaysResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVirtualGatewaysResult, error) {
			args := v.(GetVirtualGatewaysArgs)
			r, err := GetVirtualGateways(ctx, &args, opts...)
			var s GetVirtualGatewaysResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVirtualGatewaysResultOutput)
}

// A collection of arguments for invoking getVirtualGateways.
type GetVirtualGatewaysOutputArgs struct {
	Filters           GetVirtualGatewaysFilterArrayInput `pulumi:"filters"`
	VirtualGatewayIds pulumi.StringArrayInput            `pulumi:"virtualGatewayIds"`
}

func (GetVirtualGatewaysOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualGatewaysArgs)(nil)).Elem()
}

// A collection of values returned by getVirtualGateways.
type GetVirtualGatewaysResultOutput struct{ *pulumi.OutputState }

func (GetVirtualGatewaysResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVirtualGatewaysResult)(nil)).Elem()
}

func (o GetVirtualGatewaysResultOutput) ToGetVirtualGatewaysResultOutput() GetVirtualGatewaysResultOutput {
	return o
}

func (o GetVirtualGatewaysResultOutput) ToGetVirtualGatewaysResultOutputWithContext(ctx context.Context) GetVirtualGatewaysResultOutput {
	return o
}

func (o GetVirtualGatewaysResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetVirtualGatewaysResult] {
	return pulumix.Output[GetVirtualGatewaysResult]{
		OutputState: o.OutputState,
	}
}

func (o GetVirtualGatewaysResultOutput) Filters() GetVirtualGatewaysFilterArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []GetVirtualGatewaysFilter { return v.Filters }).(GetVirtualGatewaysFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVirtualGatewaysResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVirtualGatewaysResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetVirtualGatewaysResultOutput) VirtualGatewayIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []string { return v.VirtualGatewayIds }).(pulumi.StringArrayOutput)
}

func (o GetVirtualGatewaysResultOutput) VirtualGateways() GetVirtualGatewaysVirtualGatewayArrayOutput {
	return o.ApplyT(func(v GetVirtualGatewaysResult) []GetVirtualGatewaysVirtualGateway { return v.VirtualGateways }).(GetVirtualGatewaysVirtualGatewayArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVirtualGatewaysResultOutput{})
}
