// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func LookupVpnConnection(ctx *pulumi.Context, args *LookupVpnConnectionArgs, opts ...pulumi.InvokeOption) (*LookupVpnConnectionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupVpnConnectionResult
	err := ctx.Invoke("outscale:index/getVpnConnection:getVpnConnection", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVpnConnection.
type LookupVpnConnectionArgs struct {
	Filters          []GetVpnConnectionFilter `pulumi:"filters"`
	StaticRoutesOnly *bool                    `pulumi:"staticRoutesOnly"`
	VpnConnectionId  *string                  `pulumi:"vpnConnectionId"`
}

// A collection of values returned by getVpnConnection.
type LookupVpnConnectionResult struct {
	ClientGatewayConfiguration string                   `pulumi:"clientGatewayConfiguration"`
	ClientGatewayId            string                   `pulumi:"clientGatewayId"`
	ConnectionType             string                   `pulumi:"connectionType"`
	Filters                    []GetVpnConnectionFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id               string                         `pulumi:"id"`
	RequestId        string                         `pulumi:"requestId"`
	Routes           []GetVpnConnectionRouteType    `pulumi:"routes"`
	State            string                         `pulumi:"state"`
	StaticRoutesOnly *bool                          `pulumi:"staticRoutesOnly"`
	Tags             []GetVpnConnectionTag          `pulumi:"tags"`
	VgwTelemetries   []GetVpnConnectionVgwTelemetry `pulumi:"vgwTelemetries"`
	VirtualGatewayId string                         `pulumi:"virtualGatewayId"`
	VpnConnectionId  *string                        `pulumi:"vpnConnectionId"`
}

func LookupVpnConnectionOutput(ctx *pulumi.Context, args LookupVpnConnectionOutputArgs, opts ...pulumi.InvokeOption) LookupVpnConnectionResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupVpnConnectionResult, error) {
			args := v.(LookupVpnConnectionArgs)
			r, err := LookupVpnConnection(ctx, &args, opts...)
			var s LookupVpnConnectionResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(LookupVpnConnectionResultOutput)
}

// A collection of arguments for invoking getVpnConnection.
type LookupVpnConnectionOutputArgs struct {
	Filters          GetVpnConnectionFilterArrayInput `pulumi:"filters"`
	StaticRoutesOnly pulumi.BoolPtrInput              `pulumi:"staticRoutesOnly"`
	VpnConnectionId  pulumi.StringPtrInput            `pulumi:"vpnConnectionId"`
}

func (LookupVpnConnectionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpnConnectionArgs)(nil)).Elem()
}

// A collection of values returned by getVpnConnection.
type LookupVpnConnectionResultOutput struct{ *pulumi.OutputState }

func (LookupVpnConnectionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupVpnConnectionResult)(nil)).Elem()
}

func (o LookupVpnConnectionResultOutput) ToLookupVpnConnectionResultOutput() LookupVpnConnectionResultOutput {
	return o
}

func (o LookupVpnConnectionResultOutput) ToLookupVpnConnectionResultOutputWithContext(ctx context.Context) LookupVpnConnectionResultOutput {
	return o
}

func (o LookupVpnConnectionResultOutput) ToOutput(ctx context.Context) pulumix.Output[LookupVpnConnectionResult] {
	return pulumix.Output[LookupVpnConnectionResult]{
		OutputState: o.OutputState,
	}
}

func (o LookupVpnConnectionResultOutput) ClientGatewayConfiguration() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.ClientGatewayConfiguration }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) ClientGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.ClientGatewayId }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) ConnectionType() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.ConnectionType }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) Filters() GetVpnConnectionFilterArrayOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) []GetVpnConnectionFilter { return v.Filters }).(GetVpnConnectionFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupVpnConnectionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) Routes() GetVpnConnectionRouteTypeArrayOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) []GetVpnConnectionRouteType { return v.Routes }).(GetVpnConnectionRouteTypeArrayOutput)
}

func (o LookupVpnConnectionResultOutput) State() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.State }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) StaticRoutesOnly() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) *bool { return v.StaticRoutesOnly }).(pulumi.BoolPtrOutput)
}

func (o LookupVpnConnectionResultOutput) Tags() GetVpnConnectionTagArrayOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) []GetVpnConnectionTag { return v.Tags }).(GetVpnConnectionTagArrayOutput)
}

func (o LookupVpnConnectionResultOutput) VgwTelemetries() GetVpnConnectionVgwTelemetryArrayOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) []GetVpnConnectionVgwTelemetry { return v.VgwTelemetries }).(GetVpnConnectionVgwTelemetryArrayOutput)
}

func (o LookupVpnConnectionResultOutput) VirtualGatewayId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) string { return v.VirtualGatewayId }).(pulumi.StringOutput)
}

func (o LookupVpnConnectionResultOutput) VpnConnectionId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupVpnConnectionResult) *string { return v.VpnConnectionId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupVpnConnectionResultOutput{})
}
