// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetVms(ctx *pulumi.Context, args *GetVmsArgs, opts ...pulumi.InvokeOption) (*GetVmsResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVmsResult
	err := ctx.Invoke("outscale:index/getVms:getVms", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVms.
type GetVmsArgs struct {
	Filters []GetVmsFilter `pulumi:"filters"`
}

// A collection of values returned by getVms.
type GetVmsResult struct {
	Filters []GetVmsFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id        string     `pulumi:"id"`
	RequestId string     `pulumi:"requestId"`
	Vms       []GetVmsVm `pulumi:"vms"`
}

func GetVmsOutput(ctx *pulumi.Context, args GetVmsOutputArgs, opts ...pulumi.InvokeOption) GetVmsResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVmsResult, error) {
			args := v.(GetVmsArgs)
			r, err := GetVms(ctx, &args, opts...)
			var s GetVmsResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVmsResultOutput)
}

// A collection of arguments for invoking getVms.
type GetVmsOutputArgs struct {
	Filters GetVmsFilterArrayInput `pulumi:"filters"`
}

func (GetVmsOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmsArgs)(nil)).Elem()
}

// A collection of values returned by getVms.
type GetVmsResultOutput struct{ *pulumi.OutputState }

func (GetVmsResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmsResult)(nil)).Elem()
}

func (o GetVmsResultOutput) ToGetVmsResultOutput() GetVmsResultOutput {
	return o
}

func (o GetVmsResultOutput) ToGetVmsResultOutputWithContext(ctx context.Context) GetVmsResultOutput {
	return o
}

func (o GetVmsResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetVmsResult] {
	return pulumix.Output[GetVmsResult]{
		OutputState: o.OutputState,
	}
}

func (o GetVmsResultOutput) Filters() GetVmsFilterArrayOutput {
	return o.ApplyT(func(v GetVmsResult) []GetVmsFilter { return v.Filters }).(GetVmsFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVmsResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmsResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVmsResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmsResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetVmsResultOutput) Vms() GetVmsVmArrayOutput {
	return o.ApplyT(func(v GetVmsResult) []GetVmsVm { return v.Vms }).(GetVmsVmArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVmsResultOutput{})
}
