// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

func GetVmStates(ctx *pulumi.Context, args *GetVmStatesArgs, opts ...pulumi.InvokeOption) (*GetVmStatesResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetVmStatesResult
	err := ctx.Invoke("outscale:index/getVmStates:getVmStates", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getVmStates.
type GetVmStatesArgs struct {
	AllVms  *bool               `pulumi:"allVms"`
	Filters []GetVmStatesFilter `pulumi:"filters"`
	VmIds   []string            `pulumi:"vmIds"`
}

// A collection of values returned by getVmStates.
type GetVmStatesResult struct {
	AllVms  *bool               `pulumi:"allVms"`
	Filters []GetVmStatesFilter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id        string               `pulumi:"id"`
	RequestId string               `pulumi:"requestId"`
	VmIds     []string             `pulumi:"vmIds"`
	VmStates  []GetVmStatesVmState `pulumi:"vmStates"`
}

func GetVmStatesOutput(ctx *pulumi.Context, args GetVmStatesOutputArgs, opts ...pulumi.InvokeOption) GetVmStatesResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (GetVmStatesResult, error) {
			args := v.(GetVmStatesArgs)
			r, err := GetVmStates(ctx, &args, opts...)
			var s GetVmStatesResult
			if r != nil {
				s = *r
			}
			return s, err
		}).(GetVmStatesResultOutput)
}

// A collection of arguments for invoking getVmStates.
type GetVmStatesOutputArgs struct {
	AllVms  pulumi.BoolPtrInput         `pulumi:"allVms"`
	Filters GetVmStatesFilterArrayInput `pulumi:"filters"`
	VmIds   pulumi.StringArrayInput     `pulumi:"vmIds"`
}

func (GetVmStatesOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmStatesArgs)(nil)).Elem()
}

// A collection of values returned by getVmStates.
type GetVmStatesResultOutput struct{ *pulumi.OutputState }

func (GetVmStatesResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetVmStatesResult)(nil)).Elem()
}

func (o GetVmStatesResultOutput) ToGetVmStatesResultOutput() GetVmStatesResultOutput {
	return o
}

func (o GetVmStatesResultOutput) ToGetVmStatesResultOutputWithContext(ctx context.Context) GetVmStatesResultOutput {
	return o
}

func (o GetVmStatesResultOutput) ToOutput(ctx context.Context) pulumix.Output[GetVmStatesResult] {
	return pulumix.Output[GetVmStatesResult]{
		OutputState: o.OutputState,
	}
}

func (o GetVmStatesResultOutput) AllVms() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v GetVmStatesResult) *bool { return v.AllVms }).(pulumi.BoolPtrOutput)
}

func (o GetVmStatesResultOutput) Filters() GetVmStatesFilterArrayOutput {
	return o.ApplyT(func(v GetVmStatesResult) []GetVmStatesFilter { return v.Filters }).(GetVmStatesFilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetVmStatesResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmStatesResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetVmStatesResultOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v GetVmStatesResult) string { return v.RequestId }).(pulumi.StringOutput)
}

func (o GetVmStatesResultOutput) VmIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetVmStatesResult) []string { return v.VmIds }).(pulumi.StringArrayOutput)
}

func (o GetVmStatesResultOutput) VmStates() GetVmStatesVmStateArrayOutput {
	return o.ApplyT(func(v GetVmStatesResult) []GetVmStatesVmState { return v.VmStates }).(GetVmStatesVmStateArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(GetVmStatesResultOutput{})
}
