// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package outscale

import (
	"context"
	"reflect"

	"github.com/outscale-vbr/pulumi-outscale/sdk/go/outscale/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumix"
)

type ServerCertificate struct {
	pulumi.CustomResourceState

	Body           pulumi.StringPtrOutput `pulumi:"body"`
	Chain          pulumi.StringPtrOutput `pulumi:"chain"`
	DryRun         pulumi.StringPtrOutput `pulumi:"dryRun"`
	ExpirationDate pulumi.StringOutput    `pulumi:"expirationDate"`
	Name           pulumi.StringOutput    `pulumi:"name"`
	Orn            pulumi.StringOutput    `pulumi:"orn"`
	Path           pulumi.StringOutput    `pulumi:"path"`
	PrivateKey     pulumi.StringPtrOutput `pulumi:"privateKey"`
	RequestId      pulumi.StringOutput    `pulumi:"requestId"`
	UploadDate     pulumi.StringOutput    `pulumi:"uploadDate"`
}

// NewServerCertificate registers a new resource with the given unique name, arguments, and options.
func NewServerCertificate(ctx *pulumi.Context,
	name string, args *ServerCertificateArgs, opts ...pulumi.ResourceOption) (*ServerCertificate, error) {
	if args == nil {
		args = &ServerCertificateArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ServerCertificate
	err := ctx.RegisterResource("outscale:index/serverCertificate:ServerCertificate", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetServerCertificate gets an existing ServerCertificate resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetServerCertificate(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ServerCertificateState, opts ...pulumi.ResourceOption) (*ServerCertificate, error) {
	var resource ServerCertificate
	err := ctx.ReadResource("outscale:index/serverCertificate:ServerCertificate", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ServerCertificate resources.
type serverCertificateState struct {
	Body           *string `pulumi:"body"`
	Chain          *string `pulumi:"chain"`
	DryRun         *string `pulumi:"dryRun"`
	ExpirationDate *string `pulumi:"expirationDate"`
	Name           *string `pulumi:"name"`
	Orn            *string `pulumi:"orn"`
	Path           *string `pulumi:"path"`
	PrivateKey     *string `pulumi:"privateKey"`
	RequestId      *string `pulumi:"requestId"`
	UploadDate     *string `pulumi:"uploadDate"`
}

type ServerCertificateState struct {
	Body           pulumi.StringPtrInput
	Chain          pulumi.StringPtrInput
	DryRun         pulumi.StringPtrInput
	ExpirationDate pulumi.StringPtrInput
	Name           pulumi.StringPtrInput
	Orn            pulumi.StringPtrInput
	Path           pulumi.StringPtrInput
	PrivateKey     pulumi.StringPtrInput
	RequestId      pulumi.StringPtrInput
	UploadDate     pulumi.StringPtrInput
}

func (ServerCertificateState) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCertificateState)(nil)).Elem()
}

type serverCertificateArgs struct {
	Body       *string `pulumi:"body"`
	Chain      *string `pulumi:"chain"`
	DryRun     *string `pulumi:"dryRun"`
	Name       *string `pulumi:"name"`
	Path       *string `pulumi:"path"`
	PrivateKey *string `pulumi:"privateKey"`
}

// The set of arguments for constructing a ServerCertificate resource.
type ServerCertificateArgs struct {
	Body       pulumi.StringPtrInput
	Chain      pulumi.StringPtrInput
	DryRun     pulumi.StringPtrInput
	Name       pulumi.StringPtrInput
	Path       pulumi.StringPtrInput
	PrivateKey pulumi.StringPtrInput
}

func (ServerCertificateArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*serverCertificateArgs)(nil)).Elem()
}

type ServerCertificateInput interface {
	pulumi.Input

	ToServerCertificateOutput() ServerCertificateOutput
	ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput
}

func (*ServerCertificate) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCertificate)(nil)).Elem()
}

func (i *ServerCertificate) ToServerCertificateOutput() ServerCertificateOutput {
	return i.ToServerCertificateOutputWithContext(context.Background())
}

func (i *ServerCertificate) ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCertificateOutput)
}

func (i *ServerCertificate) ToOutput(ctx context.Context) pulumix.Output[*ServerCertificate] {
	return pulumix.Output[*ServerCertificate]{
		OutputState: i.ToServerCertificateOutputWithContext(ctx).OutputState,
	}
}

// ServerCertificateArrayInput is an input type that accepts ServerCertificateArray and ServerCertificateArrayOutput values.
// You can construct a concrete instance of `ServerCertificateArrayInput` via:
//
//	ServerCertificateArray{ ServerCertificateArgs{...} }
type ServerCertificateArrayInput interface {
	pulumi.Input

	ToServerCertificateArrayOutput() ServerCertificateArrayOutput
	ToServerCertificateArrayOutputWithContext(context.Context) ServerCertificateArrayOutput
}

type ServerCertificateArray []ServerCertificateInput

func (ServerCertificateArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerCertificate)(nil)).Elem()
}

func (i ServerCertificateArray) ToServerCertificateArrayOutput() ServerCertificateArrayOutput {
	return i.ToServerCertificateArrayOutputWithContext(context.Background())
}

func (i ServerCertificateArray) ToServerCertificateArrayOutputWithContext(ctx context.Context) ServerCertificateArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCertificateArrayOutput)
}

func (i ServerCertificateArray) ToOutput(ctx context.Context) pulumix.Output[[]*ServerCertificate] {
	return pulumix.Output[[]*ServerCertificate]{
		OutputState: i.ToServerCertificateArrayOutputWithContext(ctx).OutputState,
	}
}

// ServerCertificateMapInput is an input type that accepts ServerCertificateMap and ServerCertificateMapOutput values.
// You can construct a concrete instance of `ServerCertificateMapInput` via:
//
//	ServerCertificateMap{ "key": ServerCertificateArgs{...} }
type ServerCertificateMapInput interface {
	pulumi.Input

	ToServerCertificateMapOutput() ServerCertificateMapOutput
	ToServerCertificateMapOutputWithContext(context.Context) ServerCertificateMapOutput
}

type ServerCertificateMap map[string]ServerCertificateInput

func (ServerCertificateMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerCertificate)(nil)).Elem()
}

func (i ServerCertificateMap) ToServerCertificateMapOutput() ServerCertificateMapOutput {
	return i.ToServerCertificateMapOutputWithContext(context.Background())
}

func (i ServerCertificateMap) ToServerCertificateMapOutputWithContext(ctx context.Context) ServerCertificateMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ServerCertificateMapOutput)
}

func (i ServerCertificateMap) ToOutput(ctx context.Context) pulumix.Output[map[string]*ServerCertificate] {
	return pulumix.Output[map[string]*ServerCertificate]{
		OutputState: i.ToServerCertificateMapOutputWithContext(ctx).OutputState,
	}
}

type ServerCertificateOutput struct{ *pulumi.OutputState }

func (ServerCertificateOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ServerCertificate)(nil)).Elem()
}

func (o ServerCertificateOutput) ToServerCertificateOutput() ServerCertificateOutput {
	return o
}

func (o ServerCertificateOutput) ToServerCertificateOutputWithContext(ctx context.Context) ServerCertificateOutput {
	return o
}

func (o ServerCertificateOutput) ToOutput(ctx context.Context) pulumix.Output[*ServerCertificate] {
	return pulumix.Output[*ServerCertificate]{
		OutputState: o.OutputState,
	}
}

func (o ServerCertificateOutput) Body() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.Body }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) Chain() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.Chain }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) DryRun() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.DryRun }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) ExpirationDate() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.ExpirationDate }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Orn() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Orn }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) PrivateKey() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringPtrOutput { return v.PrivateKey }).(pulumi.StringPtrOutput)
}

func (o ServerCertificateOutput) RequestId() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.RequestId }).(pulumi.StringOutput)
}

func (o ServerCertificateOutput) UploadDate() pulumi.StringOutput {
	return o.ApplyT(func(v *ServerCertificate) pulumi.StringOutput { return v.UploadDate }).(pulumi.StringOutput)
}

type ServerCertificateArrayOutput struct{ *pulumi.OutputState }

func (ServerCertificateArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ServerCertificate)(nil)).Elem()
}

func (o ServerCertificateArrayOutput) ToServerCertificateArrayOutput() ServerCertificateArrayOutput {
	return o
}

func (o ServerCertificateArrayOutput) ToServerCertificateArrayOutputWithContext(ctx context.Context) ServerCertificateArrayOutput {
	return o
}

func (o ServerCertificateArrayOutput) ToOutput(ctx context.Context) pulumix.Output[[]*ServerCertificate] {
	return pulumix.Output[[]*ServerCertificate]{
		OutputState: o.OutputState,
	}
}

func (o ServerCertificateArrayOutput) Index(i pulumi.IntInput) ServerCertificateOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ServerCertificate {
		return vs[0].([]*ServerCertificate)[vs[1].(int)]
	}).(ServerCertificateOutput)
}

type ServerCertificateMapOutput struct{ *pulumi.OutputState }

func (ServerCertificateMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ServerCertificate)(nil)).Elem()
}

func (o ServerCertificateMapOutput) ToServerCertificateMapOutput() ServerCertificateMapOutput {
	return o
}

func (o ServerCertificateMapOutput) ToServerCertificateMapOutputWithContext(ctx context.Context) ServerCertificateMapOutput {
	return o
}

func (o ServerCertificateMapOutput) ToOutput(ctx context.Context) pulumix.Output[map[string]*ServerCertificate] {
	return pulumix.Output[map[string]*ServerCertificate]{
		OutputState: o.OutputState,
	}
}

func (o ServerCertificateMapOutput) MapIndex(k pulumi.StringInput) ServerCertificateOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ServerCertificate {
		return vs[0].(map[string]*ServerCertificate)[vs[1].(string)]
	}).(ServerCertificateOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCertificateInput)(nil)).Elem(), &ServerCertificate{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCertificateArrayInput)(nil)).Elem(), ServerCertificateArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ServerCertificateMapInput)(nil)).Elem(), ServerCertificateMap{})
	pulumi.RegisterOutputType(ServerCertificateOutput{})
	pulumi.RegisterOutputType(ServerCertificateArrayOutput{})
	pulumi.RegisterOutputType(ServerCertificateMapOutput{})
}
