name: run-pull-request
on:
  push:
jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.9.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: create provider
        run: make provider

